### ISSUE TITLE
develop rest api ideas for version 1

### ISSUE THREAD

**Issue by blndev** [restSampleServices/node-service#1]
place for discussing first available calls

**Comment by blndev** [comment]
Idea /api/flowers/
- get 
  Returns a list of flowers
  `flower: {
  name:"englisch flower name",
  latinName: "latin flower name",
  url: "url to wikipedia",
  image: "url to a image or empty",
  description: "wiki based description",
  readOnly: "true"
  }
  `
- post
  Allows to create a new flower
- put 
  Allows to update the flower only new flowers.
  Otherwise 403
- delete
  allow to delete new flowers, otherwise throw an 403
- /api/flowers/latinName/ - get the selected flower object
- /api/flowers/latinName/image
  get the selected flower (binary) image if available
  Note: images should be cached on the service

**Comment by blndev** [comment]
Idea: /chat/{room}/

Features: 
- Web Sockets per Room
- Create Rooms
- Create private Rooms (need basic auth key)

Questions:
- how to handle users

Idea /gallery/
Features
- upload / download images to / from a dedicated folder
- creating directory / gallery
- post /gallery/{name}/ allows upload, retun is a galleryImage Object with identifier (hash of file)
- /gallery/{name}/{fileId}/ gets one file
- /gallery/{name}/{fileId}/comments - allows to create / list comments on the picture

**Comment by dabperceptive** [comment]
we will combine chat with gallery. instead of only text messages there can be also an image send to a room

**Comment by blndev** [comment]
chat will be version 2, version 1 contains only the employees service.
